apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor_worker
spec:
  replicas: 2 # Adjust based on your load requirements
  selector:
    matchLabels:
      app: monitor_worker_app
  template:
    metadata:
      labels:
        app: monitor_worker_app
    spec:
      containers:
      - name: monitor_worker
        image: monitor_worker:latest  # Replace with your Docker image
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"  # RabbitMQ service name in Kubernetes
        ports:
        - containerPort: 8080
